/**
 * PrimeVue Configuration
 *
 * تنظیمات PrimeVue برای استفاده در پروژه
 * - RTL support
 * - Tree-shaking: فقط کامپوننت‌های موردنیاز import می‌شوند
 */

// تنظیمات PrimeVue
export const primevueConfig = {
  ripple: false,
  inputStyle: 'outlined',
  locale: {
    startsWith: 'شروع با',
    contains: 'شامل',
    notContains: 'شامل نمی‌شود',
    endsWith: 'پایان با',
    equals: 'برابر',
    notEquals: 'برابر نیست',
    noFilter: 'بدون فیلتر',
    lt: 'کمتر از',
    lte: 'کمتر یا برابر',
    gt: 'بیشتر از',
    gte: 'بیشتر یا برابر',
    dateIs: 'تاریخ برابر',
    dateIsNot: 'تاریخ برابر نیست',
    dateBefore: 'قبل از تاریخ',
    dateAfter: 'بعد از تاریخ',
    clear: 'پاک کردن',
    apply: 'اعمال',
    matchAll: 'همه موارد',
    matchAny: 'هر کدام',
    addRule: 'افزودن قانون',
    removeRule: 'حذف قانون',
    accept: 'بله',
    reject: 'خیر',
    choose: 'انتخاب',
    upload: 'آپلود',
    cancel: 'لغو',
    dayNames: ['یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه', 'شنبه'],
    dayNamesShort: ['یک', 'دو', 'سه', 'چهار', 'پنج', 'جم', 'شن'],
    dayNamesMin: ['ی', 'د', 'س', 'چ', 'پ', 'ج', 'ش'],
    monthNames: [
      'ژانویه',
      'فوریه',
      'مارس',
      'آوریل',
      'می',
      'ژوئن',
      'ژوئیه',
      'اوت',
      'سپتامبر',
      'اکتبر',
      'نوامبر',
      'دسامبر',
    ],
    monthNamesShort: [
      'ژان',
      'فور',
      'مار',
      'آور',
      'می',
      'ژوئن',
      'ژوئ',
      'اوت',
      'سپت',
      'اکت',
      'نوا',
      'دسا',
    ],
    today: 'امروز',
    weekHeader: 'هفته',
    firstDayOfWeek: 6, // شنبه
    dateFormat: 'yy/mm/dd',
    weak: 'ضعیف',
    medium: 'متوسط',
    strong: 'قوی',
    passwordPrompt: 'رمز عبور را وارد کنید',
    emptyFilterMessage: 'نتیجه‌ای یافت نشد',
    emptyMessage: 'گزینه‌ای موجود نیست',
    aria: {
      trueLabel: 'درست',
      falseLabel: 'غلط',
      nullLabel: 'انتخاب نشده',
      star: 'ستاره',
      heart: 'قلب',
      badge: 'نشان',
      selectAll: 'انتخاب همه',
      unselectAll: 'لغو انتخاب همه',
      close: 'بستن',
      previous: 'قبلی',
      next: 'بعدی',
      navigation: 'ناوبری',
      scrollTop: 'اسکرول به بالا',
      moveTop: 'انتقال به بالا',
      moveUp: 'انتقال به بالا',
      moveDown: 'انتقال به پایین',
      moveBottom: 'انتقال به پایین',
      moveToTarget: 'انتقال به هدف',
      moveToSource: 'انتقال به منبع',
      moveAllToTarget: 'انتقال همه به هدف',
      moveAllToSource: 'انتقال همه به منبع',
      pageLabel: 'صفحه {page}',
      firstPageLabel: 'صفحه اول',
      lastPageLabel: 'صفحه آخر',
      nextPageLabel: 'صفحه بعد',
      prevPageLabel: 'صفحه قبل',
      rowsPerPageLabel: 'تعداد ردیف در هر صفحه',
      jumpToPageDropdownLabel: 'پرش به صفحه',
      jumpToPageInputLabel: 'پرش به صفحه',
      selectRow: 'انتخاب ردیف',
      unselectRow: 'لغو انتخاب ردیف',
      expandRow: 'باز کردن ردیف',
      collapseRow: 'بستن ردیف',
      showFilterMenu: 'نمایش منوی فیلتر',
      hideFilterMenu: 'مخفی کردن منوی فیلتر',
      filterOperator: 'عملگر فیلتر',
      filterConstraint: 'محدودیت فیلتر',
      editRow: 'ویرایش ردیف',
      saveEdit: 'ذخیره ویرایش',
      cancelEdit: 'لغو ویرایش',
      listView: 'نمایش لیست',
      gridView: 'نمایش شبکه',
      slide: 'اسلاید',
      slideNumber: '{slideNumber}',
      zoomImage: 'بزرگنمایی تصویر',
      zoomIn: 'بزرگنمایی',
      zoomOut: 'کوچکنمایی',
      rotateRight: 'چرخش به راست',
      rotateLeft: 'چرخش به چپ',
    },
  },
}
